FROM python:3.10-slim

WORKDIR /app
COPY . .

RUN apt update && apt -y install git
RUN pip install -r requirements_dht.txt 
RUN pip install --no-deps hivemind 

ENV DHT_PORT=5555 DOCKER_IP="0.0.0.0"
    
ENTRYPOINT ["/app/run_dht.sh"]

